wx:
  appid: wxe2b6df99eaa2054a
  secret: b12bc25dba4fbfe1983d18fd9cc3e9e8
  expire_time: 86400000
upload:
  imageHost: http://111.230.220.64:8080
  imagePath: /usr/local/src/image
hot:
  search:
    score: 1000
  weibo:
    forward-score: 2000
    comment-score: 3000
    like-score: 1000
appeal:
  weibo-limit: 10
  comment-limit: 10
  user-limit: 10
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weibo?autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 3116004646
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 20 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 150 #最大连接数
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  mvc:
    static-path-pattern: /images/**
  resources:
    static-locations: file:/usr/local/src/image/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    password: 111
logging:
  level:
    com.yamada.weibo.mapper: debug

