wx:
  appid: wxe2b6df99eaa2054a
  secret: b12bc25dba4fbfe1983d18fd9cc3e9e8
  expire_time: 86400000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weibo?autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.yamada.weibo.mapper: debug